
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ProstateRehabilitationAlliance/Config.git
          search-paths: respo
          default-label: master

server:
  port: 8880