spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ProstateRehabilitationAlliance/Config.git
          search-paths: respo
          default-label: master
    discovery:
      enabled: true
      serviceId: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.1.222:8888/eureka/
server:
  port: 8880
